# define L_ARROW	"\e[D"
# define U_ARROW	"\e[A"
# define D_ARROW	"\e[B"
# define R_ARROW	"\e[C"

# define F1			"\eOP"
# define F2			"\eOQ"
# define F3			"\eOR"
# define F4			"\eOS"
# define F5			"\e[15~"
# define F6			"\e[17~"
# define F7			"\e[18~"
# define F8			"\e[19~"
# define F9			"\e[20~"
# define F10		"\e[21~"
# define F12		"\e[24~"

# define CTRL_A		"\01"
# define CTRL_B		"\02"
# define CTRL_C		"\03"
# define CTRL_D		"\04"
# define CTRL_E		"\05"
# define CTRL_F		"\06"
# define CTRL_G		"\07"
# define CTRL_H		"\10"
# define CTRL_I		"\11"
//# define CTRL_J		"\12"
# define CTRL_K		"\13"
# define CTRL_L		"\14"
# define CTRL_M		"\12"
# define CTRL_N		"\16"
# define CTRL_O		"\17"
# define CTRL_P		"\20"
//# define CTRL_Q		""
# define CTRL_R		"\22"
//# define CTRL_S		""
# define CTRL_T		"\24"
# define CTRL_U		"\25"
# define CTRL_V		"\26"
# define CTRL_W		"\27"
# define CTRL_X		"\30"
# define CTRL_Y		"\31"
# define CTRL_Z		"\32"

# define NULBYTE		0
# define LINEFEED		"\xA"
# define ENTER			10
# define BACKSPACE		127
# define ESCAPE			"\e"
/*
**	Warning: arrows begin with ESCAPE character
*/

# define ALT_A			"\xC3" "\xA5"
# define ALT_B			"\xE2" "\x88" "\xAB"
# define ALT_C			"\xC3" "\xA7"
# define ALT_D			"\xE2" "\x88" "\x82"
# define ALT_E			"\xC2" "\xB4"
# define ALT_F			"\xC6" "\x92"
# define ALT_G			"\xC2" "\xA9"
# define ALT_H			"\xCB" "\x99"
# define ALT_I			"\xCB" "\x86"
# define ALT_J			"\xE2" "\x88" "\x86"
# define ALT_K			"\xCB" "\x9A"
# define ALT_L			"\xC2" "\xAC"
# define ALT_M			"\xC2" "\xB5"
# define ALT_N			"\xCB" "\x9C"
# define ALT_O			"\xC3" "\xB8"
# define ALT_P			"\xCF" "\x80"
# define ALT_Q			"\xC5" "\x93"
# define ALT_R			"\xC2" "\xAE"
# define ALT_S			"\xC3" "\x9F"
# define ALT_T			"\xE2" "\x80" "\xA0"
# define ALT_U			"\xC2" "\xA8"
# define ALT_V			"\xE2" "\x88" "\x9A"
# define ALT_W			"\xE2" "\x88" "\x91"
# define ALT_X			"\xE2" "\x89" "\x88"
//# define ALT_Y			""
# define ALT_Z			"\xCE" "\xA9"


/*
# define ALT_MAJ_A			"\x" "\x"
# define ALT_MAJ_B			"\x" "\x"
# define ALT_MAJ_C			"\x" "\x"
# define ALT_MAJ_D			"\x" "\x"
# define ALT_MAJ_E			"\x" "\x"
# define ALT_MAJ_F			"\x" "\x"
# define ALT_MAJ_G			"\x" "\x"
# define ALT_MAJ_H			"\x" "\x"
# define ALT_MAJ_I			"\x" "\x"
# define ALT_MAJ_J			"\x" "\x"
# define ALT_MAJ_K			"\x" "\x"
# define ALT_MAJ_L			"\x" "\x"
# define ALT_MAJ_M			"\x" "\x"
# define ALT_MAJ_N			"\x" "\x"
# define ALT_MAJ_O			"\x" "\x"
# define ALT_MAJ_P			"\x" "\x"
# define ALT_MAJ_Q			"\x" "\x"
# define ALT_MAJ_R			"\x" "\x"
# define ALT_MAJ_S			"\x" "\x"
# define ALT_MAJ_T			"\x" "\x"
# define ALT_MAJ_U			"\x" "\x"
# define ALT_MAJ_V			"\x" "\x"
# define ALT_MAJ_W			"\x" "\x"
# define ALT_MAJ_X			"\x" "\x"
# define ALT_MAJ_Y			"\x" "\x"
# define ALT_MAJ_Z			"\x" "\x"
*/

# define PASTE_START		"\e[200~"
# define PASTE_END			"\e[201~"
